#! /bin/sh
### BEGIN INIT INFO
# Provides:          hb-restore-fstab
# Required-Start:    
# Required-Stop:     
# Default-Start:     0 1 2 3 4 5 6
# Default-Stop:      
# Short-Description: Restore a clean fstab file
# Description:       Copies /etc/fstab-clean over /etc/fstab
### END INIT INFO

# Author: Foo Bar <foobar@baz.org>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
DESC="Restore a clean fstab file"
NAME=hb-restore-fstab
SCRIPTNAME=/etc/init.d/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
copy_clean_fstab()
{
	cp /etc/fstab-clean /etc/fstab
	return 0
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Restoring clean fstab file"
	copy_clean_fstab
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  install)
	cp $0 "/etc/init.d/`basename $0`"
	chmod 755 "/etc/init.d/`basename $0`"
	update-rc.d "`basename $0`" start 00 0 1 2 3 4 5 6 .
	cp /etc/fstab /etc/fstab-clean
	;;
  *)
	echo "Usage: `basename $0` {start|install}" >&2
	exit 3
	;;
esac
